name: docker_build_push

on:
  push:
    branches: main 
jobs: 

#Docker image build using binary created      
  image_build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Image bulid
      run: docker build -t go/hello .
#login to Docker registry 
    - name: Login to Docker Registry
#    - uses: docker/login-action@v1
      env: 
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }} 
      run: echo  "$docker_password" | docker login kcdev1.krypc.com:5000 -u "$docker_username" --password-stdin

