name: docker_build_push

on:
  push:
    branches: main 
#    tags:
#      - 'v.*'
jobs: 

#Docker image build using binary created      
  docker_login:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      env: 
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }} 
      run: echo  "$docker_password" | docker login kcdev1.krypc.com:5000 -u "$docker_username" --password-stdin

#Tag and push images

  tag_and_push:
    needs: image_build
    runs-on: self-hosted
    steps:
    - uses: docker/build-push-action@v1
    - name: Image tag and push
      env: 
        
      run: |
        docker build -t go/hello -f Dockerfile . -t kcdev1.krypc.com:5000/gohello:latest
        docker images
 #       docker tag go/hello:latest kcdev1.krypc.com:5000/gohello:v1
 #       docker push  kcdev1.krypc.com:5000/gohello:v1
