name: AWS_VM_LOGIN
on:
  workflow_run:
    workflows: ["docker_build_push"]
    types:
      - completed 
jobs:
  VM_LOGIN:
    runs-on: self-hosted
    steps:
#     - name: checkout
#       uses: actions/checkout@v2  
    - name: Login to AWS VM
      uses: easingthemes/ssh-deploy@main
      env: 
        SSH_SSH_KEY: ${{secrets.SERVER_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}



