name: CI docker_build

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed   

jobs: 

  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Running unit tests
  Run_unit_tests:
    runs-on: self-hosted
    steps:
    - name: Running unit tests
      run: go test ./hello -v

#Docker image build using binary created      
  image_build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Image bulid
      run: docker build -t go/hello .  
