name: CI docker_build

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed   

jobs: 

#Docker image build using binary created      
  image_build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Image bulid
      run: docker build -t go/hello .  
