name:

on:
  push:
    branches: main
  pull_request:
    brances: main
 
jobs: 

#Docker image build using binary created      
  image_build:
    needs: image_build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Image bulid
      run: docker build -t go/hello .
#login to Docker registry 
    - name: Login to Docker Registry
#    - uses: docker/login-action@v1
      env: 
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }} 
      run: echo  "$docker_password" | docker login kcdev1.krypc.com:5000 -u "$docker_username" --password-stdin

#Tag and push images

  tag_and_push:
  #- name: Build and push Docker images
    needs: image_build
    runs-on: self-hosted
    steps:
    - uses: docker/build-push-action@v1
   # - uses: docker/build-push-action@v2.5.0
    - name: Image tag and push
      run: |
        docker build -t go/hello -f Dockerfile .
        docker tag go/hello:latest kcdev1.krypc.com:5000/gohello:v1
        docker push  kcdev1.krypc.com:5000/gohello:v1
