name: Go

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Removing old binary file   
    - name: Binary remove
      run: rm -r main
 
#Creating a binary file
    - name: Build
      run: go build main.go
      
#Docker image build using binary created      
    - name: Docker Image
      run: docker build -t go/hello .
   
 name: Go

on:
  push:
    branches: vaishakh-test
  pull_request:
    branches: vaishakh-test
      
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16    
       
#Removing old binary file   
    - name: Binary remove
      run: rm -r main
 
#Creating a binary file
    - name: Build
      run: go build main.go       
