name: Go

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Removing old binary file   
    - name: Binary remove
      run: rm -r main
 
#Creating a binary file
    - name: Build
      run: go build main.go
      
#Docker image build using binary created      
    - name: Docker Image
      run: docker build -t go/hello .
      
#login to Docker registry
#   # - uses: docker/login-action@v1 
    - name: Login to Docker Registry
    env: 
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }} 
      run: echo  "$docker_password" | docker login kcdev1.krypc.com:5000 -u "$docker_username" --password-stdin
#       run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login kcdev1.krypc.com:5000 -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
