name: Go

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Removing old binary file   
    - name: Binary remove
      run: |
       rm -r main
       echo "remove binary"
#Testing go file   
    - name: Run tests
      run: go test main.go
 
#Creating a binary file
    - name: Build
      run: go build main.go
#Cache dependancies
    - name: Cache Files
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
#**Script added for docker image build**
#   script_docker_build:
#       needs: build
#       runs-on: self-hosted
#       steps:
#         - uses: actions/checkout@v2
#           with: 
#            ref: main
#         - run: chmod +x ./templates/scripts/docker_build.sh
#         - run: sh ./templates/scripts/docker_build.sh
#           shell: bash
          
          
#   build_image:
#       needs: build
#       runs-on: self-hosted
#       steps:
#         - uses: actions/checkout@v2
#           with: 
#            branches: main
# #         - uses: krypc-code/research-working-group@v1
# #         - run: pwd
#         - run: /home/git_sys/actions-runner/_work/research-working-group/research-working-group/ci.yml
