name: Go

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Removing old binary file   
    - name: Binary remove
      run: rm -r main
      
#Testing go file   
    - name: Run tests
      run: go test main.go
 
#Creating a binary file
    - name: Build
      run: go build main.go
      
#   build_image:
#       needs: build
#       runs-on: self-hosted
#       steps:
#         - uses: actions/checkout@v2
#         - template: ./templates/ci/docker_build_push.yml    
