name: pytest

on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  Setup python:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        
   Run a Script:
    - name: Run script.
      env:
        Name: "Krypc"
      run: python pytest.py $Name
      
      
    
