
name: Go - main

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Removing old binary file   
    - name: Binary remove
      run: rm -r main
      
#Running unit tests
    - name: Running unit tests
      run: go test ./hello -v
 
#Creating a binary file
    - name: Build
      run: go build main.go
      
#Docker image build using binary created      
    - name: Docker Image
      run: docker build -t go/hello .
