
name: Go-CI

on:
  push:
    branches: main
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Login to Docker Registry
      env: 
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }} 
      run: echo  "$docker_password" | docker login kcdev1.krypc.com:5000 -u "$docker_username" --password-stdin        

#Running unit tests
    - name: Running unit tests
      run: go test ./hello -v

#Removing old binary file   
    - name: Binary remove
      run: rm -r main 

#Creating a binary file
    - name: Go_Build
      run: |
       go build main.go
       echo ${{ github.sha }}
       
    - name: Docker_Build       
       docker build -t helloworld . 
       docker tag helloworld kcdev1.krypc.com:5000/hellosha:${{ github.sha }}
       docker tag helloworld kcdev1.krypc.com:5000/hellosha:latest
       
    - name: Push
      run: |
       docker push kcdev1.krypc.com:5000/hellosha:${{ github.sha }}
       docker push kcdev1.krypc.com:5000/hellosha:latest
      

