
name: Go-CI

on:
  push:
    branches: main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Running unit tests
    - name: Running unit tests
      run: go test ./hello -v
#Removing old binary file   
    - name: Binary remove
      run: rm -r main 
#Creating a binary file
    - name: Build
      run: |
        go build main.go
        echo ${{ github.sha }}
        docker build -t helloworld -f Dockerfile . -t taggedimage/helloworld:${{ github.sha }}
        echo docker images | grep taggedimage/helloworld
      

